baseURL = "https://gallonhu.github.io"
languageCode = "en-us"
title = "Waking up"
theme = "journal"

[params]
  description = "Blog meta description."
  githubUsername = "gallonhu"
  tagline = "Anything in life worth doing is worth overdoing. Moderation is for cowards."
