baseURL = "https://gallonhu.github.io"
languageCode = "en-us"
title = "Keep Going"
theme = "journal"

[params]
  description = "Blog meta description."
  githubUsername = "gallonhu"
  tagline = "Learning and coding"
